/**
 * Gera output/migration.sql a partir de posts-pt.json + posts-en.json
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { prefixedTable } from "../../../src/db/table-prefix.ts";
import type { MigrationData, MigrationImage, MigrationPost } from "./types.ts";
import {
  MIGRATION_SQL,
  OUTPUT_DIR,
  POSTS_EN_JSON,
  POSTS_PT_JSON,
} from "./paths.ts";

const T = prefixedTable;
const MIGRATION_TS = Math.floor(Date.now() / 1000);

function escapeSql(s: string): string {
  return s.replace(/'/g, "''");
}

function attachmentSlug(postSlug: string, image: MigrationImage): string {
  const safe = image.relativePath.replace(/[^a-zA-Z0-9_-]/g, "-");
  return `blog-media-${postSlug}-${safe}`;
}

function isUploadableImage(image: MigrationImage): boolean {
  if (image.filename.startsWith(".")) return false;
  return image.mimeType.startsWith("image/") || image.mimeType.startsWith("video/");
}

function collectAllImages(posts: MigrationPost[]): Map<string, MigrationImage & { ownerSlug: string }> {
  const map = new Map<string, MigrationImage & { ownerSlug: string }>();
  for (const post of posts) {
    for (const image of post.images) {
      if (!isUploadableImage(image)) continue;
      const slug = attachmentSlug(post.slug.replace(/-en$/, ""), image);
      if (!map.has(slug)) {
        map.set(slug, { ...image, ownerSlug: post.slug.replace(/-en$/, "") });
      }
    }
  }
  return map;
}

function generateSql(pt: MigrationData, en: MigrationData): string {
  const lines: string[] = [
    "-- Blog rhamses migration (idempotent). Generated by 2-generate-sql.ts",
    "",
    `-- Taxonomia Blog`,
    `INSERT OR IGNORE INTO ${T("taxonomies")} (name, slug, type, parent_id, created_at, updated_at)`,
    `SELECT 'Blog', 'blog', 'category', (SELECT id FROM ${T("taxonomies")} WHERE slug='categoria' LIMIT 1), ${MIGRATION_TS}, ${MIGRATION_TS}`,
    `WHERE NOT EXISTS (SELECT 1 FROM ${T("taxonomies")} WHERE slug='blog');`,
    "",
    `-- Tema blog-rhamses (post type themes)`,
    `INSERT OR IGNORE INTO ${T("posts")} (post_type_id, title, slug, status, meta_values, created_at, updated_at)`,
    `SELECT (SELECT id FROM ${T("post_types")} WHERE slug='themes' LIMIT 1), 'Blog Rhamsés', 'blog-rhamses', 'published', '${escapeSql(JSON.stringify({ theme_slug: "blog-rhamses", version: "1.0.0" }))}', ${MIGRATION_TS}, ${MIGRATION_TS}`,
    `WHERE NOT EXISTS (SELECT 1 FROM ${T("posts")} WHERE slug='blog-rhamses');`,
    "",
  ];

  const allPosts = [...pt.posts, ...en.posts];
  const attachments = collectAllImages(allPosts);

  lines.push("-- Attachments (imagens do blog)");
  for (const [attSlug, image] of attachments) {
    const meta = escapeSql(
      JSON.stringify({
        mime_type: image.mimeType,
        attachment_file: image.filename,
        attachment_path: `/${image.r2Key}`,
        attachment_alt: image.filename,
      }),
    );
    lines.push(
      `INSERT OR IGNORE INTO ${T("posts")} (post_type_id, title, slug, status, meta_values, created_at, updated_at)`,
      `SELECT (SELECT id FROM ${T("post_types")} WHERE slug='attachment' LIMIT 1), '${escapeSql(image.filename)}', '${escapeSql(attSlug)}', 'published', '${meta}', ${MIGRATION_TS}, ${MIGRATION_TS}`,
      `WHERE NOT EXISTS (SELECT 1 FROM ${T("posts")} WHERE slug='${escapeSql(attSlug)}');`,
    );
  }
  lines.push("");

  function coverAttachmentSlug(post: MigrationPost): string | null {
    if (!post.coverImage) return null;
    const baseSlug = post.slug.replace(/-en$/, "");
    return attachmentSlug(baseSlug, post.coverImage);
  }

  function insertPost(post: MigrationPost, localeCode: string): void {
    const locale = localeCode === "en" ? "en_US" : "pt_BR";
    const coverSlug = coverAttachmentSlug(post);
    const metaBase: Record<string, string> = { translation_key: post.translation_key };
    const body = escapeSql(post.body_html);
    const title = escapeSql(post.title);
    const slug = escapeSql(post.slug);
    const excerpt = escapeSql(post.description);
    const publishedAt = post.publishedAt;

    lines.push(
      `INSERT OR IGNORE INTO ${T("posts")} (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)`,
      `SELECT (SELECT id FROM ${T("post_types")} WHERE slug='post' LIMIT 1), (SELECT id FROM ${T("locales")} WHERE locale_code='${locale}' LIMIT 1), '${title}', '${slug}', '${excerpt}', '${body}', 'published', '${escapeSql(JSON.stringify(metaBase))}', ${publishedAt}, ${MIGRATION_TS}, ${MIGRATION_TS}`,
      `WHERE NOT EXISTS (SELECT 1 FROM ${T("posts")} WHERE slug='${slug}');`,
      `UPDATE ${T("posts")} SET title='${title}', excerpt='${excerpt}', body='${body}', updated_at=${MIGRATION_TS} WHERE slug='${slug}';`,
    );

    if (coverSlug) {
      lines.push(
        `UPDATE ${T("posts")} SET meta_values=json_object('translation_key', '${escapeSql(post.translation_key)}', 'post_thumbnail_id', CAST((SELECT id FROM ${T("posts")} WHERE slug='${escapeSql(coverSlug)}' LIMIT 1) AS TEXT)) WHERE slug='${slug}';`,
        `INSERT OR IGNORE INTO ${T("posts_media")} (post_id, media_id)`,
        `SELECT (SELECT id FROM ${T("posts")} WHERE slug='${slug}' LIMIT 1), (SELECT id FROM ${T("posts")} WHERE slug='${escapeSql(coverSlug)}' LIMIT 1)`,
        `WHERE NOT EXISTS (SELECT 1 FROM ${T("posts_media")} WHERE post_id=(SELECT id FROM ${T("posts")} WHERE slug='${slug}' LIMIT 1) AND media_id=(SELECT id FROM ${T("posts")} WHERE slug='${escapeSql(coverSlug)}' LIMIT 1));`,
      );
    }

    lines.push(
      `INSERT OR IGNORE INTO ${T("posts_taxonomies")} (post_id, term_id)`,
      `SELECT (SELECT id FROM ${T("posts")} WHERE slug='${slug}' LIMIT 1), (SELECT id FROM ${T("taxonomies")} WHERE slug='blog' LIMIT 1)`,
      `WHERE NOT EXISTS (SELECT 1 FROM ${T("posts_taxonomies")} WHERE post_id=(SELECT id FROM ${T("posts")} WHERE slug='${slug}' LIMIT 1) AND term_id=(SELECT id FROM ${T("taxonomies")} WHERE slug='blog' LIMIT 1));`,
      `INSERT OR IGNORE INTO ${T("seo_metadata")} (post_id, seo_title, seo_description, created_at, updated_at)`,
      `SELECT (SELECT id FROM ${T("posts")} WHERE slug='${slug}' LIMIT 1), '${title}', '${excerpt}', ${MIGRATION_TS}, ${MIGRATION_TS}`,
      `WHERE NOT EXISTS (SELECT 1 FROM ${T("seo_metadata")} WHERE post_id=(SELECT id FROM ${T("posts")} WHERE slug='${slug}' LIMIT 1));`,
      `UPDATE ${T("seo_metadata")} SET seo_title='${title}', seo_description='${excerpt}', updated_at=${MIGRATION_TS} WHERE post_id=(SELECT id FROM ${T("posts")} WHERE slug='${slug}' LIMIT 1);`,
      "",
    );
  }

  lines.push("-- Posts PT-BR");
  for (const post of pt.posts) {
    insertPost(post, "pt-br");
  }

  lines.push("-- Posts EN");
  for (const post of en.posts) {
    insertPost(post, "en");
  }

  lines.push(
    "-- Settings",
    `UPDATE ${T("settings")} SET value='blog-rhamses' WHERE name='active_theme';`,
    `UPDATE ${T("settings")} SET value='Rhamsés Blog' WHERE name='site_name';`,
    `UPDATE ${T("settings")} SET value='Articles about software engineering and Web development.' WHERE name='site_description';`,
    "",
  );

  return lines.join("\n");
}

function main(): void {
  const pt: MigrationData = JSON.parse(readFileSync(POSTS_PT_JSON, "utf8"));
  const en: MigrationData = JSON.parse(readFileSync(POSTS_EN_JSON, "utf8"));
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const sql = generateSql(pt, en);
  writeFileSync(MIGRATION_SQL, sql, "utf8");
  console.log(`[generate-sql] → ${MIGRATION_SQL}`);
}

main();
